'use strict';
const crypto=require('node:crypto');
const dns=require('node:dns').promises;
const {getPool}=require('../db');
const config=require('../config');
const sig=require('../utils/r2-sigv4');

const MiB=1024*1024;
const GiB=1024*1024*1024;
const DEFAULT_TARGET=10*GiB;
const DEFAULT_PART=5*MiB;
const MAX_PART_BUFFER=64*MiB;
const MAX_FILE_SIZE=10*GiB;

function httpError(message,status=400){return Object.assign(new Error(message),{status})}
function cleanText(v,max=500){return String(v??'').trim().slice(0,max)}
function cleanPrefix(v){return String(v??'').replace(/\\/g,'/').split('/').map(s=>s.replace(/[\0-\x1F\x7F]/g,' ').replace(/\s+/g,' ').trim()).filter(s=>s&&s!=='.'&&s!=='..').map(s=>s.slice(0,240)).join('/')}
function sanitizeFilename(v){const raw=String(v||'file.bin').replace(/[\\/\0-\x1F\x7F]/g,' ').replace(/\s+/g,' ').trim();return(raw||'file.bin').slice(0,240)}
function extensionOf(filename){const m=String(filename).match(/(\.[a-zA-Z0-9]{1,12})$/);return m?m[1].toLowerCase():''}
function opaqueToken(bytes=24){return crypto.randomBytes(bytes).toString('base64url')}
function objectKeyHash(key){return crypto.createHash('sha256').update(String(key)).digest()}
function encodeKey(key){return String(key).split('/').map(sig.rfc3986).join('/')}
function endpointFor(account){
  const cf=cleanText(account.cloudflare_account_id||account.account_id,80);
  if(!cf||!/^[a-zA-Z0-9_-]+$/.test(cf))throw httpError('Cloudflare Account ID is invalid.');
  return `https://${cf}.r2.cloudflarestorage.com`;
}
function credentialMaterial(){return String(config.r2CredentialsKey||config.sessionSecret||'')}
function credentialKey(){const m=credentialMaterial();if(m.length<16)throw httpError('Set R2_CREDENTIALS_KEY (or a strong SESSION_SECRET) before saving R2 credentials.',409);return crypto.createHash('sha256').update(m).digest()}
function encryptSecret(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',credentialKey(),iv);const body=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return['v1',iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),body.toString('base64url')].join(':')}
function decryptSecret(value){const parts=String(value||'').split(':');if(parts.length!==4||parts[0]!=='v1')throw httpError('Saved R2 secret cannot be decrypted. Re-enter the account secret.',409);const dec=crypto.createDecipheriv('aes-256-gcm',credentialKey(),Buffer.from(parts[1],'base64url'));dec.setAuthTag(Buffer.from(parts[2],'base64url'));return Buffer.concat([dec.update(Buffer.from(parts[3],'base64url')),dec.final()]).toString('utf8')}
function accountJson(row){
  const used=Number(row.indexed_bytes||0),capacity=Number(row.storage_target_bytes||DEFAULT_TARGET)||DEFAULT_TARGET;
  return{id:Number(row.id),label:row.label,enabled:Boolean(row.enabled),cloudflareAccountId:row.cloudflare_account_id,bucket:row.bucket_name,accessKeyId:row.access_key_id,hasSecret:Boolean(row.secret_encrypted),storageTargetBytes:capacity,indexedBytes:used,remainingBytes:Math.max(0,capacity-used),usagePercent:capacity?Math.min(100,Math.round(used/capacity*1000)/10):0,indexedObjects:Number(row.indexed_objects||0),lastTestStatus:row.last_test_status||'not_tested',lastTestMessage:row.last_test_message||'',lastTestAt:row.last_test_at||null,lastSyncAt:row.last_sync_at||null,createdAt:row.created_at,updatedAt:row.updated_at}
}
async function accountRow(id,{secret=false}={}){const db=getPool();const[[row]]=await db.query(`SELECT a.*,(SELECT COALESCE(SUM(o.size_bytes),0) FROM r2_objects o WHERE o.account_id=a.id AND o.object_key NOT LIKE '%/') indexed_bytes,(SELECT COUNT(*) FROM r2_objects o WHERE o.account_id=a.id AND o.object_key NOT LIKE '%/') indexed_objects FROM r2_accounts a WHERE a.id=? LIMIT 1`,[Number(id)]);if(!row)return null;if(secret)row.secret_access_key=decryptSecret(row.secret_encrypted);return row}
async function accounts(){const[rows]=await getPool().query(`SELECT a.*,(SELECT COALESCE(SUM(o.size_bytes),0) FROM r2_objects o WHERE o.account_id=a.id AND o.object_key NOT LIKE '%/') indexed_bytes,(SELECT COUNT(*) FROM r2_objects o WHERE o.account_id=a.id AND o.object_key NOT LIKE '%/') indexed_objects FROM r2_accounts a ORDER BY enabled DESC,id ASC`);return rows.map(accountJson)}
async function saveAccount(input,id=0){
  const db=getPool(),label=cleanText(input.label,160),cf=cleanText(input.cloudflareAccountId||input.accountId,80),bucket=cleanText(input.bucket,255),access=cleanText(input.accessKeyId,255),secret=String(input.secretAccessKey||''),enabled=input.enabled!==false;
  if(!label||!cf||!bucket||!access)throw httpError('Account label, Cloudflare Account ID, bucket name, and Access Key ID are required.');
  const endpoint=endpointFor({cloudflare_account_id:cf});
  if(!id&&!secret)throw httpError('Secret Access Key is required for a new R2 account.');
  if(id){
    const existing=await accountRow(id);if(!existing)throw httpError('R2 account not found.',404);const enc=secret?encryptSecret(secret):existing.secret_encrypted;
    await db.query(`UPDATE r2_accounts SET label=?,enabled=?,cloudflare_account_id=?,bucket_name=?,access_key_id=?,secret_encrypted=?,folder_prefix=NULL,endpoint_url=?,region='auto',link_mode='gateway',direct_domain='',gateway_domain='',storage_target_bytes=? WHERE id=?`,[label,enabled?1:0,cf,bucket,access,enc,endpoint,DEFAULT_TARGET,Number(id)]);
    return accountJson(await accountRow(id));
  }
  const enc=encryptSecret(secret);const[r]=await db.query(`INSERT INTO r2_accounts(label,enabled,cloudflare_account_id,bucket_name,access_key_id,secret_encrypted,folder_prefix,endpoint_url,region,link_mode,direct_domain,gateway_domain,storage_target_bytes) VALUES (?,?,?,?,?,?,NULL,?,'auto','gateway','','',?)`,[label,enabled?1:0,cf,bucket,access,enc,endpoint,DEFAULT_TARGET]);return accountJson(await accountRow(r.insertId));
}
async function removeAccount(id){const db=getPool();const[[active]]=await db.query(`SELECT COUNT(*) count FROM r2_uploads WHERE account_id=? AND status IN ('starting','uploading','completing')`,[Number(id)]);if(Number(active?.count||0))throw httpError('Abort active uploads for this account before deleting it.',409);const[r]=await db.query('DELETE FROM r2_accounts WHERE id=?',[Number(id)]);if(!r.affectedRows)throw httpError('R2 account not found.',404);return true}

function normalizeDomainHost(value){let raw=String(value||'').trim().toLowerCase();if(!raw)throw httpError('Enter a download subdomain.');if(!raw.includes('://'))raw='https://'+raw;let u;try{u=new URL(raw)}catch{throw httpError('Download domain is invalid.')}const host=u.hostname.toLowerCase().replace(/^\.+|\.+$/g,'');if(!host||host==='localhost'||/^\d+(?:\.\d+){3}$/.test(host)||host.includes(':')||host.length>253)throw httpError('Use a public DNS hostname such as downloads.example.com.');if(!/^[a-z0-9.-]+$/.test(host)||!host.includes('.'))throw httpError('Use a valid public DNS hostname.');return host}
function routingHost(value){try{const raw=String(value||'').trim();const u=new URL(raw.includes('://')?raw:'https://'+raw);const h=u.hostname.toLowerCase();if(!h||h==='localhost'||/^\d+(?:\.\d+){3}$/.test(h))return'';return h}catch{return''}}
function domainJson(row,appHost=''){const host=row.hostname;const target=routingHost(appHost);return{id:Number(row.id),hostname:host,verified:Boolean(row.verified_at),verifiedAt:row.verified_at||null,active:Boolean(row.active),txtName:`_appbit-verification.${host}`,txtValue:`appbit-verification=${row.verification_token}`,cnameName:host,cnameTarget:target,publicBase:`https://${host}`,createdAt:row.created_at,updatedAt:row.updated_at}}
async function domains(appHost=''){const[rows]=await getPool().query('SELECT * FROM r2_download_domains ORDER BY active DESC,verified_at DESC,id DESC');return rows.map(r=>domainJson(r,appHost))}
async function addDomain(value,appHost=''){const db=getPool(),hostname=normalizeDomainHost(value),token=opaqueToken(24);await db.query(`INSERT INTO r2_download_domains(hostname,verification_token,active) VALUES (?,?,0) ON DUPLICATE KEY UPDATE verified_at=NULL,active=0`,[hostname,token]);const[[row]]=await db.query('SELECT * FROM r2_download_domains WHERE hostname=? LIMIT 1',[hostname]);return domainJson(row,appHost)}
async function verifyDownloadGateway(hostname,appHost=''){
  const expectedHost=routingHost(appHost);if(!expectedHost)throw httpError('Open Appbit through its public Hostinger hostname before verifying a download domain.',409);
  let response;try{response=await fetch(`https://${hostname}/api/health/public`,{method:'GET',redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'Accept':'application/json','User-Agent':'Appbit-Domain-Verify/2.20'}})}catch(e){throw httpError(`DNS TXT is correct, but HTTPS for ${hostname} is not reaching Appbit. A CNAME alone is not enough: the hostname must have a valid SSL certificate and route to the Appbit Hostinger app. Gateway check failed: ${e.message}`,409)}
  if(!response.ok)throw httpError(`DNS TXT is correct, but HTTPS gateway check returned HTTP ${response.status}. Configure ${hostname} so https://${hostname}/api/health/public reaches this Appbit deployment, then verify again.`,409);
  let body=null;try{body=await response.json()}catch{}
  if(!body||typeof body!=='object'||!body.version)throw httpError(`DNS TXT is correct, but ${hostname} is not serving the Appbit gateway. Configure the hostname/SSL first, then verify again.`,409);
  return true;
}
async function verifyDomain(id,appHost=''){
  const db=getPool();const[[row]]=await db.query('SELECT * FROM r2_download_domains WHERE id=? LIMIT 1',[Number(id)]);if(!row)throw httpError('Download domain not found.',404);
  const name=`_appbit-verification.${row.hostname}`,expected=`appbit-verification=${row.verification_token}`;let values=[];try{const records=await dns.resolveTxt(name);values=records.map(parts=>parts.join('').replace(/[\s\u200b]+/g,''))}catch(e){if(!['EAI_AGAIN','ECONNREFUSED','ECONNRESET','ENODATA','ENETUNREACH','ENOTFOUND','ESERVFAIL','ETIMEOUT'].includes(String(e.code||'')))throw e}
  if(!values.some(value=>value===expected))throw httpError(`TXT record not found yet. Add ${name} with value ${expected}, wait for DNS propagation, then verify again.`,409);
  await verifyDownloadGateway(row.hostname,appHost);
  const conn=await db.getConnection();try{await conn.beginTransaction();await conn.query('UPDATE r2_download_domains SET active=0');await conn.query('UPDATE r2_download_domains SET verified_at=NOW(),active=1 WHERE id=?',[row.id]);await conn.commit()}catch(e){await conn.rollback();throw e}finally{conn.release()}
  const[[fresh]]=await db.query('SELECT * FROM r2_download_domains WHERE id=? LIMIT 1',[row.id]);return domainJson(fresh,appHost);
}
async function removeDomain(id){const[r]=await getPool().query('DELETE FROM r2_download_domains WHERE id=?',[Number(id)]);if(!r.affectedRows)throw httpError('Download domain not found.',404);return true}
async function activeDownloadHost(){const[[row]]=await getPool().query('SELECT hostname FROM r2_download_domains WHERE active=1 AND verified_at IS NOT NULL ORDER BY id DESC LIMIT 1');return row?.hostname||''}
function publicUrlForToken(token,host=''){return host?`https://${host}/d/${encodeURIComponent(token)}`:`/d/${encodeURIComponent(token)}`}
function publicFilename(value){const parts=String(value||'').replace(/\\/g,'/').split('/').filter(Boolean);return sanitizeFilename(parts.pop()||'download')}
function publicUrlForFilename(filename,host=''){const leaf=encodeURIComponent(sanitizeFilename(filename));return host?`https://${host}/${leaf}`:`/${leaf}`}
function publicUrlForKey(key,host=''){return publicUrlForFilename(publicFilename(key),host)}
function incomingHost(value){return String(value||'').trim().toLowerCase().replace(/:\d+$/,'').replace(/^\.+|\.+$/g,'')}

function xmlDecode(v){return String(v||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&')}
function xmlEscape(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function xmlTag(xml,name){const m=String(xml||'').match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,'i'));return m?xmlDecode(m[1].trim()):''}
function errorMessage(xml,fallback){const code=xmlTag(xml,'Code'),msg=xmlTag(xml,'Message');return[code,msg].filter(Boolean).join(': ')||fallback||'R2 request failed.'}
function requestUrl(account,key='',query={}){const endpoint=endpointFor(account),bucket=sig.rfc3986(account.bucket_name),path=key?`/${bucket}/${encodeKey(key)}`:`/${bucket}`;const u=new URL(endpoint+path);for(const[k,v]of Object.entries(query||{})){if(v!==undefined&&v!==null)u.searchParams.append(k,String(v))}return u.toString()}
async function request(account,{method='GET',key='',query={},body=null,headers={},timeoutMs=30000,stream=false,range=''}){
  const secret=account.secret_access_key||decryptSecret(account.secret_encrypted);const url=requestUrl(account,key,query);const bodyBuffer=body==null?Buffer.alloc(0):Buffer.isBuffer(body)?body:Buffer.from(String(body));const payloadHash=sig.sha256Hex(bodyBuffer);const h={...headers};if(range)h.Range=range;if(body!=null&&!Object.keys(h).some(k=>k.toLowerCase()==='content-length'))h['Content-Length']=String(bodyBuffer.length);
  const signed=sig.signRequest({method,url,accessKeyId:account.access_key_id,secretAccessKey:secret,region:'auto',headers:h,payloadHash});const opts={method,headers:signed.headers,redirect:'manual'};if(body!=null)opts.body=bodyBuffer;if(timeoutMs)opts.signal=AbortSignal.timeout(timeoutMs);
  let response;try{response=await fetch(url,opts)}catch(e){throw httpError(`R2 connection failed: ${e.message}`,502)}
  if(stream){if(!response.ok&&response.status!==206){const text=await response.text().catch(()=>'');throw httpError(errorMessage(text,`R2 returned HTTP ${response.status}.`),response.status>=400&&response.status<600?response.status:502)}return response}
  const text=method==='HEAD'?'':await response.text();if(!response.ok){const status=response.status===404?404:502;throw httpError(errorMessage(text,`R2 returned HTTP ${response.status}.`),status)}return{status:response.status,text,headers:response.headers,url}
}
function parseList(xml){const objects=[];const re=/<Contents>([\s\S]*?)<\/Contents>/gi;let m;while((m=re.exec(String(xml||'')))){const block=m[1],key=xmlTag(block,'Key');if(!key)continue;objects.push({key,size:Number(xmlTag(block,'Size')||0),etag:xmlTag(block,'ETag').replace(/^"|"$/g,''),lastModified:xmlTag(block,'LastModified')||null})}return{objects,isTruncated:String(xmlTag(xml,'IsTruncated')).toLowerCase()==='true',nextToken:xmlTag(xml,'NextContinuationToken')}}
async function listPage(account,{prefix='',maxKeys=1000,token=''}={}){const q={'list-type':'2','max-keys':Math.max(1,Math.min(1000,Number(maxKeys)||1000))};if(prefix)q.prefix=prefix;if(token)q['continuation-token']=token;const out=await request(account,{query:q});return parseList(out.text)}
async function testAccount(id){const db=getPool(),account=await accountRow(id,{secret:true});if(!account)throw httpError('R2 account not found.',404);try{const page=await listPage(account,{prefix:'',maxKeys:3});const msg=`Connected to ${account.bucket_name}.`;await db.query(`UPDATE r2_accounts SET last_test_status='success',last_test_message=?,last_test_at=NOW() WHERE id=?`,[msg,Number(id)]);return{ok:true,message:msg,sample:page.objects}}catch(e){await db.query(`UPDATE r2_accounts SET last_test_status='failed',last_test_message=?,last_test_at=NOW() WHERE id=?`,[String(e.message).slice(0,900),Number(id)]);throw e}}
async function syncAccount(id,{maxPages=50}={}){const db=getPool(),account=await accountRow(id,{secret:true});if(!account)throw httpError('R2 account not found.',404);const stamp=new Date().toISOString().slice(0,19).replace('T',' ');let token='',count=0,pages=0,bytes=0;do{const page=await listPage(account,{prefix:'',maxKeys:1000,token});for(const obj of page.objects){const isFolder=obj.key.endsWith('/')&&obj.size===0,name=sanitizeFilename((obj.key.split('/').filter(Boolean).pop())||(isFolder?'Folder':'file')),publicToken=opaqueToken(24);await db.query(`INSERT INTO r2_objects(account_id,key_hash,object_key,filename,size_bytes,etag,last_modified,public_token,last_seen_at,source) VALUES (?,?,?,?,?,?,?,?,?,'sync') ON DUPLICATE KEY UPDATE filename=VALUES(filename),size_bytes=VALUES(size_bytes),etag=VALUES(etag),last_modified=VALUES(last_modified),last_seen_at=VALUES(last_seen_at)`,[account.id,objectKeyHash(obj.key),obj.key,name,obj.size,obj.etag||null,obj.lastModified?new Date(obj.lastModified):null,publicToken,stamp]);if(!isFolder){count++;bytes+=obj.size}}pages++;token=page.isTruncated?page.nextToken:''}while(token&&pages<maxPages);if(!token)await db.query('DELETE FROM r2_objects WHERE account_id=? AND last_seen_at<?',[account.id,stamp]);await db.query('UPDATE r2_accounts SET last_sync_at=NOW() WHERE id=?',[account.id]);return{count,bytes,pages,truncated:Boolean(token)}}
async function chooseAccount(fileSize=0){const rows=await accounts(),enabled=rows.filter(a=>a.enabled);if(!enabled.length)throw httpError('No enabled R2 account is available.',409);const fit=enabled.filter(a=>a.indexedBytes+Number(fileSize||0)<=a.storageTargetBytes);return(fit.length?fit:enabled).sort((a,b)=>a.indexedBytes-b.indexedBytes)[0]}
function partSizeForFile(size){const n=Math.max(0,Number(size)||0);let part=DEFAULT_PART;if(n>50*GiB)part=16*MiB;if(n>120*GiB)part=32*MiB;if(n>300*GiB)part=64*MiB;const needed=Math.ceil(n/9999);if(needed>part)part=Math.ceil(needed/MiB)*MiB;if(part>MAX_PART_BUFFER)throw httpError('This file requires multipart chunks larger than Appbit’s 64 MiB proxy limit.',413);return part}
function makeObjectKey({account,filename,keyMode='name',objectKey=''}){if(objectKey){const cleaned=String(objectKey).replace(/\\/g,'/').split('/').map((s,i,a)=>i===a.length-1?sanitizeFilename(s):cleanPrefix(s)).filter(Boolean).join('/');if(!cleaned)throw httpError('Object key is invalid.');return cleaned}const ext=extensionOf(filename),leaf=keyMode==='opaque'?`${opaqueToken(18)}${ext}`:sanitizeFilename(filename);return leaf}
async function startUpload({accountId,filename,size,contentType,lastModifiedMs,keyMode='name',objectKey='',replaceObjectId=0,createdBy=0,resumeToken=''}){
  const db=getPool(),fileName=sanitizeFilename(filename),fileSize=Number(size);if(!Number.isFinite(fileSize)||fileSize<0)throw httpError('File size is invalid.');if(fileSize>MAX_FILE_SIZE)throw httpError('Files up to 10 GB are supported. Choose a smaller file.',413);if(!fileName)throw httpError('File name is required.');if(resumeToken){const existing=await uploadByToken(resumeToken);if(existing&&existing.status==='uploading'&&existing.filename===fileName&&Number(existing.file_size_bytes)===fileSize&&Number(existing.last_modified_ms||0)===Number(lastModifiedMs||0))return uploadJson(existing)}
  let account,replace=null,token=opaqueToken(24),key='';if(replaceObjectId){const[[row]]=await db.query('SELECT * FROM r2_objects WHERE id=? LIMIT 1',[Number(replaceObjectId)]);if(!row)throw httpError('R2 object to replace was not found.',404);replace=row;account=await accountRow(row.account_id,{secret:true});key=row.object_key;token=row.public_token}else{account=Number(accountId)>0?await accountRow(accountId,{secret:true}):await accountRow((await chooseAccount(fileSize)).id,{secret:true});if(!account)throw httpError('R2 account not found.',404);if(!account.enabled)throw httpError('This R2 account is disabled.',409);key=makeObjectKey({account,filename:fileName,keyMode,objectKey})}
  const contentDisposition=`attachment; filename*=UTF-8''${sig.rfc3986(fileName)}`;const out=await request(account,{method:'POST',key,query:{uploads:''},headers:{'Content-Type':cleanText(contentType,180)||'application/octet-stream','Content-Disposition':contentDisposition},body:Buffer.alloc(0)});const uploadId=xmlTag(out.text,'UploadId');if(!uploadId)throw httpError('R2 did not return a multipart UploadId.',502);const partSize=partSizeForFile(fileSize),uploadToken=opaqueToken(24);const[r]=await db.query(`INSERT INTO r2_uploads(upload_token,account_id,r2_upload_id,object_key,filename,file_size_bytes,content_type,last_modified_ms,part_size_bytes,parts_json,status,replace_object_id,public_token,created_by) VALUES (?,?,?,?,?,?,?,?,?,'{}','uploading',?,?,?)`,[uploadToken,account.id,uploadId,key,fileName,fileSize,cleanText(contentType,180)||'application/octet-stream',Number(lastModifiedMs||0),partSize,replace?Number(replace.id):null,token,Number(createdBy)||null]);return uploadJson(await uploadById(r.insertId))
}
async function uploadById(id){const[[row]]=await getPool().query('SELECT * FROM r2_uploads WHERE id=? LIMIT 1',[Number(id)]);return row||null}
async function uploadByToken(token){const[[row]]=await getPool().query('SELECT * FROM r2_uploads WHERE upload_token=? LIMIT 1',[String(token)]);return row||null}
function partsObject(row){try{const o=JSON.parse(row.parts_json||'{}');return o&&typeof o==='object'&&!Array.isArray(o)?o:{}}catch{return{}}}
function uploadJson(row){const parts=partsObject(row);return{id:Number(row.id),token:row.upload_token,accountId:Number(row.account_id),objectKey:row.object_key,filename:row.filename,size:Number(row.file_size_bytes),contentType:row.content_type,partSize:Number(row.part_size_bytes),partCount:Math.max(1,Math.ceil(Number(row.file_size_bytes)/Number(row.part_size_bytes))),uploadedBytes:Number(row.uploaded_bytes||0),completedParts:Object.keys(parts).map(Number).sort((a,b)=>a-b),status:row.status,error:row.error_message||'',publicToken:row.public_token,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at||null}}
async function uploadPart(token,partNumber,buffer){const row=await uploadByToken(token);if(!row)throw httpError('Upload session not found.',404);if(row.status!=='uploading')throw httpError(`Upload is ${row.status}, not accepting parts.`,409);const part=Math.trunc(Number(partNumber)),partSize=Number(row.part_size_bytes),fileSize=Number(row.file_size_bytes),count=Math.max(1,Math.ceil(fileSize/partSize));if(part<1||part>count)throw httpError('Multipart part number is out of range.');const start=(part-1)*partSize,expected=Math.max(0,Math.min(partSize,fileSize-start));if(!Buffer.isBuffer(buffer)||buffer.length!==expected)throw httpError(`Part ${part} expected ${expected} bytes but received ${buffer?.length||0}.`,400);const account=await accountRow(row.account_id,{secret:true});if(!account)throw httpError('R2 account was removed.',409);const md5=crypto.createHash('md5').update(buffer).digest('base64');const out=await request(account,{method:'PUT',key:row.object_key,query:{partNumber:String(part),uploadId:row.r2_upload_id},headers:{'Content-Type':'application/octet-stream','Content-MD5':md5},body:buffer,timeoutMs:15*60*1000});const etag=String(out.headers.get('etag')||'').replace(/^"|"$/g,'');if(!etag)throw httpError(`R2 did not return an ETag for part ${part}.`,502);const conn=await getPool().getConnection();try{await conn.beginTransaction();const[[locked]]=await conn.query('SELECT parts_json FROM r2_uploads WHERE id=? FOR UPDATE',[row.id]);const parts=(()=>{try{return JSON.parse(locked.parts_json||'{}')||{}}catch{return{}}})();parts[String(part)]={etag,size:buffer.length};const uploaded=Object.values(parts).reduce((s,p)=>s+Number(p.size||0),0);await conn.query('UPDATE r2_uploads SET parts_json=?,uploaded_bytes=?,error_message=NULL WHERE id=?',[JSON.stringify(parts),uploaded,row.id]);await conn.commit();return{partNumber:part,etag,uploadedBytes:uploaded}}catch(e){await conn.rollback();throw e}finally{conn.release()}}
async function completeUpload(token){const db=getPool(),row=await uploadByToken(token);if(!row)throw httpError('Upload session not found.',404);if(row.status==='completed')return uploadJson(row);if(row.status!=='uploading')throw httpError(`Upload is ${row.status}.`,409);const parts=partsObject(row),partCount=Math.max(1,Math.ceil(Number(row.file_size_bytes)/Number(row.part_size_bytes)));for(let i=1;i<=partCount;i++)if(!parts[String(i)]?.etag)throw httpError(`Part ${i} has not finished uploading.`,409);await db.query(`UPDATE r2_uploads SET status='completing' WHERE id=?`,[row.id]);const account=await accountRow(row.account_id,{secret:true});try{const body=`<CompleteMultipartUpload>${Array.from({length:partCount},(_,i)=>`<Part><PartNumber>${i+1}</PartNumber><ETag>&quot;${xmlEscape(parts[String(i+1)].etag)}&quot;</ETag></Part>`).join('')}</CompleteMultipartUpload>`;const out=await request(account,{method:'POST',key:row.object_key,query:{uploadId:row.r2_upload_id},headers:{'Content-Type':'application/xml'},body});const etag=(xmlTag(out.text,'ETag')||'').replace(/^"|"$/g,''),head=await request(account,{method:'HEAD',key:row.object_key}),remoteSize=Number(head.headers.get('content-length')||0);if(remoteSize&&remoteSize!==Number(row.file_size_bytes))throw httpError(`R2 completed the object with ${remoteSize} bytes; Appbit expected ${row.file_size_bytes}.`,502);await db.query(`INSERT INTO r2_objects(account_id,key_hash,object_key,filename,content_type,size_bytes,etag,last_modified,public_token,last_seen_at,source) VALUES (?,?,?,?,?,?,?,?,?,NOW(),'upload') ON DUPLICATE KEY UPDATE filename=VALUES(filename),content_type=VALUES(content_type),size_bytes=VALUES(size_bytes),etag=VALUES(etag),last_modified=VALUES(last_modified),public_token=COALESCE(public_token,VALUES(public_token)),last_seen_at=NOW(),source='upload'`,[row.account_id,objectKeyHash(row.object_key),row.object_key,row.filename,row.content_type,row.file_size_bytes,etag||head.headers.get('etag')?.replace(/^"|"$/g,'')||null,new Date(),row.public_token]);await db.query(`UPDATE r2_uploads SET status='completed',uploaded_bytes=file_size_bytes,completed_at=NOW(),error_message=NULL WHERE id=?`,[row.id]);return uploadJson(await uploadById(row.id))}catch(e){await db.query(`UPDATE r2_uploads SET status='uploading',error_message=? WHERE id=?`,[String(e.message).slice(0,1000),row.id]);throw e}}
async function abortUpload(token){const db=getPool(),row=await uploadByToken(token);if(!row)throw httpError('Upload session not found.',404);if(['completed','aborted'].includes(row.status))return uploadJson(row);const account=await accountRow(row.account_id,{secret:true});try{await request(account,{method:'DELETE',key:row.object_key,query:{uploadId:row.r2_upload_id}})}catch(e){if(e.status!==404)throw e}await db.query(`UPDATE r2_uploads SET status='aborted',error_message=NULL WHERE id=?`,[row.id]);return uploadJson(await uploadById(row.id))}
async function getUpload(token){const row=await uploadByToken(token);return row?uploadJson(row):null}
async function listUploads(limit=25){const[rows]=await getPool().query(`SELECT * FROM r2_uploads ORDER BY id DESC LIMIT ?`,[Math.max(1,Math.min(100,Number(limit)||25))]);return rows.map(uploadJson)}
function objectJson(row,downloadHost=''){return{id:Number(row.id),accountId:Number(row.account_id),accountLabel:row.account_label,key:row.object_key,filename:row.filename,size:Number(row.size_bytes||0),contentType:row.content_type||'',etag:row.etag||'',lastModified:row.last_modified||null,uploadedAt:row.created_at||null,publicToken:row.public_token,publicUrl:publicUrlForFilename(row.filename,downloadHost),source:row.source||'sync'}}
function folderEntries(rows,prefix=''){const base=cleanPrefix(prefix),start=base?`${base}/`:'';const found=new Map();for(const row of rows){const key=String(row.object_key||'');if(!key.startsWith(start))continue;const relative=key.slice(start.length);if(!relative)continue;const segment=relative.split('/')[0];if(!segment||!relative.includes('/'))continue;const folderKey=`${start}${segment}/`,mapKey=`${Number(row.account_id)}:${folderKey}`;if(!found.has(mapKey))found.set(mapKey,{name:segment,key:folderKey,accountId:Number(row.account_id),accountLabel:row.account_label})}return[...found.values()].sort((a,b)=>a.name.localeCompare(b.name)||a.accountId-b.accountId)}
async function listObjects({accountId=0,q='',prefix='',limit=100,offset=0}={}){
  const db=getPool(),where=[],params=[],cleanedPrefix=cleanPrefix(prefix),search=String(q||'').trim().slice(0,180),accountNumber=Number(accountId)||0;
  if(accountNumber>0){where.push('o.account_id=?');params.push(accountNumber)}
  if(cleanedPrefix){where.push('o.object_key LIKE ?');params.push(`${cleanedPrefix}/%`)}
  if(search){where.push('(o.filename LIKE ? OR o.object_key LIKE ?)');const v=`%${search}%`;params.push(v,v)}
  const sql=where.length?'WHERE '+where.join(' AND '):'';
  const[rows]=await db.query(`SELECT o.*,a.label account_label FROM r2_objects o JOIN r2_accounts a ON a.id=o.account_id ${sql} ORDER BY o.last_modified DESC,o.id DESC LIMIT 5000`,params);
  const downloadHost=await activeDownloadHost(),base=cleanedPrefix?`${cleanedPrefix}/`:'';
  const folders=search?[]:folderEntries(rows,cleanedPrefix);
  let files=rows.filter(row=>!String(row.object_key||'').endsWith('/'));
  if(!search){files=files.filter(row=>{const key=String(row.object_key||'');if(!key.startsWith(base))return false;return !key.slice(base.length).includes('/')})}
  const total=files.length,lim=Math.max(1,Math.min(500,Number(limit)||100)),off=Math.max(0,Number(offset)||0);
  return{total,prefix:cleanedPrefix,folders,items:files.slice(off,off+lim).map(r=>objectJson(r,downloadHost))}
}
async function createFolder(accountId,{prefix='',name=''}={}){const db=getPool(),account=await accountRow(accountId,{secret:true});if(!account)throw httpError('R2 account not found.',404);if(!account.enabled)throw httpError('This R2 account is disabled.',409);const raw=cleanPrefix(name),parts=raw.split('/').filter(Boolean);if(parts.length!==1||!parts[0])throw httpError('Enter one folder name without a slash.');const parent=cleanPrefix(prefix),key=`${[parent,parts[0]].filter(Boolean).join('/')}/`;const[[existing]]=await db.query('SELECT * FROM r2_objects WHERE account_id=? AND key_hash=? LIMIT 1',[account.id,objectKeyHash(key)]);if(existing)return{ id:Number(existing.id),accountId:Number(account.id),name:parts[0],key,existing:true};await request(account,{method:'PUT',key,headers:{'Content-Type':'application/x-directory'},body:Buffer.alloc(0),timeoutMs:60000});const publicToken=opaqueToken(24);const[r]=await db.query(`INSERT INTO r2_objects(account_id,key_hash,object_key,filename,content_type,size_bytes,etag,last_modified,public_token,last_seen_at,source) VALUES (?,?,?,?,?,?,?,NOW(),? ,NOW(),'sync')`,[account.id,objectKeyHash(key),key,parts[0],'application/x-directory',0,null,publicToken]);return{id:Number(r.insertId),accountId:Number(account.id),name:parts[0],key,existing:false}}
async function deleteObject(id){const db=getPool();const[[row]]=await db.query('SELECT * FROM r2_objects WHERE id=? LIMIT 1',[Number(id)]);if(!row)throw httpError('R2 object not found.',404);const account=await accountRow(row.account_id,{secret:true});try{await request(account,{method:'DELETE',key:row.object_key})}catch(e){if(e.status!==404)throw e}await db.query('DELETE FROM r2_objects WHERE id=?',[row.id]);return true}
async function state(appHost=''){const db=getPool(),list=await accounts();const[[o]]=await db.query(`SELECT COUNT(*) total,COALESCE(SUM(size_bytes),0) bytes FROM r2_objects WHERE object_key NOT LIKE '%/'`),[[u]]=await db.query(`SELECT COUNT(*) active FROM r2_uploads WHERE status IN ('starting','uploading','completing')`),domainList=await domains(appHost);const capacity=list.reduce((s,a)=>s+a.storageTargetBytes,0),used=list.reduce((s,a)=>s+a.indexedBytes,0);return{accounts:list.length,enabledAccounts:list.filter(a=>a.enabled).length,objects:Number(o.total||0),indexedBytes:Number(o.bytes||0),trackedCapacityBytes:capacity,trackedRemainingBytes:Math.max(0,capacity-used),activeUploads:Number(u.active||0),activeDomain:domainList.find(d=>d.active)||null}}
async function streamObject(obj,{range='',head=false}={}){const account={...obj,secret_access_key:decryptSecret(obj.secret_encrypted)},response=await request(account,{method:head?'HEAD':'GET',key:obj.object_key,stream:true,timeoutMs:0,range});return{response,filename:obj.filename||sanitizeFilename(obj.object_key.split('/').pop()),size:Number(obj.size_bytes||0),contentType:obj.content_type||response.headers.get('content-type')||'application/octet-stream'}}
async function streamByToken(token,{range='',head=false}={}){const db=getPool();const[[obj]]=await db.query(`SELECT o.*,a.* FROM r2_objects o JOIN r2_accounts a ON a.id=o.account_id WHERE o.public_token=? LIMIT 1`,[String(token)]);if(!obj)throw httpError('Download link not found.',404);return streamObject(obj,{range,head})}
async function isActiveDownloadHost(host){const h=incomingHost(host);if(!h)return false;const[[row]]=await getPool().query('SELECT id FROM r2_download_domains WHERE hostname=? AND active=1 AND verified_at IS NOT NULL LIMIT 1',[h]);return Boolean(row)}
async function streamByPath(pathValue,{range='',head=false}={}){
  const requested=String(pathValue||'').replace(/^\/+|\/+$/g,'');if(!requested)throw httpError('Download file not found.',404);
  const db=getPool(),filename=publicFilename(requested);let obj=null;
  // V2.18 compatibility: an older folder/path URL can still resolve by its exact object key.
  if(requested.includes('/')){const[[legacy]]=await db.query(`SELECT o.*,a.* FROM r2_objects o JOIN r2_accounts a ON a.id=o.account_id WHERE o.object_key=? AND o.object_key NOT LIKE '%/' ORDER BY o.last_modified DESC,o.id DESC LIMIT 1`,[requested]);obj=legacy||null}
  // Current public contract: folders are virtual organization only. The public URL resolves by filename.
  if(!obj){const[[current]]=await db.query(`SELECT o.*,a.* FROM r2_objects o JOIN r2_accounts a ON a.id=o.account_id WHERE o.filename=? AND o.object_key NOT LIKE '%/' ORDER BY o.last_modified DESC,o.id DESC LIMIT 1`,[filename]);obj=current||null}
  if(!obj)throw httpError('Download file not found.',404);return streamObject(obj,{range,head})
}
function objectPublicUrl(account,obj,downloadHost=''){return publicUrlForFilename(obj.filename||publicFilename(obj.object_key),downloadHost)}
module.exports={accounts,saveAccount,removeAccount,testAccount,syncAccount,state,listObjects,createFolder,deleteObject,startUpload,uploadPart,completeUpload,abortUpload,getUpload,listUploads,streamByToken,streamByPath,isActiveDownloadHost,partSizeForFile,makeObjectKey,encryptSecret,decryptSecret,endpointFor,objectPublicUrl,DEFAULT_TARGET,MAX_FILE_SIZE,MAX_PART_BUFFER,domains,addDomain,verifyDomain,removeDomain,normalizeDomainHost,publicUrlForToken,publicUrlForFilename,publicUrlForKey,verifyDownloadGateway};
