from pathlib import Path
p=Path('public/ui/app.js');s=p.read_text();a=s.index('function detailHtml(x){');b=s.index('\nfunction safeSourceUrl',a)
f=r'''function detailHtml(x){
 const m=x.sourceMeta||{},media=x.media||{};
 const sourceVersion=x.sourceVersion||m.version||x.version;
 const shots=Array.isArray(m.screenshots)&&m.screenshots.length?m.screenshots.slice(0,24):(Array.isArray(media.screenshots)?media.screenshots.slice(0,24):[]);
 const hasIcon=Boolean(m.iconUrl||media.iconUrl),hasCover=Boolean(m.coverImageUrl||media.coverImageUrl);
 const play=verifiedPlayUrl(m.playStoreUrl)||verifiedPlayUrl(x.officialUrl),source=safeSourceUrl(x.sourcePageUrl||m.sourcePageUrl);
 const historyUrl=source&&safeSourceUrl(x.historyPageUrl||m.historyPageUrl,source);
 const mediaBase=`/api/apps/${x.id}/media`,stamp=encodeURIComponent(x.metadataUpdatedAt||x.updatedAt||'0');
 const mediaUrl=kind=>`${mediaBase}/${kind}?inline=1&v=${stamp}`;
 const description=x.description||'No description was reported by the source.';
 const metadata=[['App Name',x.name],['Developer',x.developer||m.developer||'Not reported'],['Category',x.category||'Other'],['Current Version',sourceVersion||'Not reported'],['Update Date',date(x.sourceUpdatedAt||m.updatedDate||m.updated)],['App Size',bytes(x.fileSizeBytes??m.fileSizeBytes)],['Requires Android',x.minimumOsVersion||m.requiresAndroid||'Not reported'],['APK Type',x.apkType||m.apkType||'APK'],['Architecture',x.architecture||'Android'],['Language',x.language||'Not reported'],['Rating',x.ratingValue==null?'Not reported':`${x.ratingValue}/5`],['Downloads',x.downloadCount==null?'Not reported':(m.downloadCountLabel&&m.downloadCount!=null&&Number(m.downloadCount)===Number(x.downloadCount)?m.downloadCountLabel:fmt(x.downloadCount))]];
 const technical=[['Package ID',x.sourcePackageId||x.packageId||'Not reported']];
 const allText=metadata.map(([label,value])=>`${label}: ${value}`).join('\n')+(play?`\nOfficial Play Store: ${play}`:'')+`\n\nDescription\n${description}`;
 const iconHtml=hasIcon?`<img src="${mediaUrl('icon')}" alt="${esc(x.name)} icon" loading="eager">`:`<span class="workspace-icon-empty">${esc((x.name||'A').slice(0,1))}</span>`;
 const versions=(x.versions||[]).filter(v=>v.version&&v.version!==x.version&&v.version!==sourceVersion&&safeSourceUrl(v.sourcePageUrl,source)&&safeSourceUrl(v.sourcePageUrl,source)!==source);
 const missing=[!x.developer&&!m.developer?'Developer':null,!x.sourceUpdatedAt&&!m.updatedDate&&!m.updated?'Update date':null,!(x.fileSizeBytes??m.fileSizeBytes)?'App size':null,x.downloadCount==null&&m.downloadCount==null?'Downloads':null].filter(Boolean);
 const linkValue=(url,label)=>url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'Not available';
 return`<div class="app-workspace app-record-page" data-record-id="${x.id}">
 <header class="record-toolbar"><div class="record-identity"><div class="record-app-icon">${iconHtml}</div><div class="record-identity-text"><div class="record-name-line"><h1>${esc(x.name)}</h1><span class="record-version">v${esc(sourceVersion||'—')}</span><span class="status ${x.published?'published':'draft'}">${x.published?'Published':'Draft'}</span>${x.updateAvailable?'<span class="status update">Update available</span>':''}</div><div class="record-subline">${esc(x.category||'Other')} · ${esc(x.developer||m.developer||'Developer not reported')}</div></div></div><div class="record-actions"><button class="btn" id="copyAppAll" data-copy="${esc(allText)}">Copy</button><button class="btn ${x.published?'':'primary'}" id="togglePublish">${x.published?'Unpublish':'Publish'}</button><button class="btn" id="refreshApp">Refresh</button><button class="btn" id="refreshMedia">Media Refresh</button><button class="btn" id="closeDetail">Back</button></div></header>
 <div id="detailMessage" class="record-message" aria-live="polite"></div>
 ${x.updateAvailable?`<div class="notice amber"><b>Source update detected.</b> ${esc(x.updateError||'Review the latest version before publishing.')}</div>`:''}
 <section class="panel record-section record-artwork-section"><div class="record-section-head"><h2>App Artwork</h2>${hasIcon||hasCover||shots.length?`<a class="btn primary" href="/api/apps/${x.id}/media.zip">Download Media</a>`:''}</div><div class="record-artwork-row"><div class="record-icon-preview">${iconHtml}<span>Icon</span></div><div class="record-cover-preview">${hasCover?`<img src="${mediaUrl('cover')}" alt="${esc(x.name)} cover" loading="eager">`:'<div class="record-cover-empty">No cover saved.</div>'}<span>Cover</span></div><div class="record-screenshot-strip">${shots.length?shots.map((_,i)=>`<div class="record-shot-preview"><img src="${mediaBase}/screenshot/${i}?inline=1&v=${stamp}" loading="lazy" alt="${esc(x.name)} screenshot ${i+1}"><span>Screenshot ${i+1}</span></div>`).join(''):'<div class="record-cover-empty">No screenshots saved.</div>'}</div></div></section>
 <div class="record-columns"><section class="panel record-section record-metadata-section"><div class="record-section-head"><h2>APK Metadata</h2></div>${missing.length?`<div class="record-missing-notice">Not reported by the latest source scan: ${esc(missing.join(', '))}. Existing data is preserved.</div>`:''}<div class="record-fields">${metadata.map(([label,value])=>field(label,esc(value))).join('')}</div><details class="record-technical"><summary>Technical ID</summary><div class="record-fields">${technical.map(([label,value])=>field(label,esc(value))).join('')}</div></details></section>
 <section class="panel record-section record-links-section"><div class="record-section-head"><h2>Links</h2></div><div class="record-links">${field('Google Play Store',linkValue(play,'Open Google Play'),play)}${field('LiteAPKs Source',linkValue(source,'Open Source'))}${historyUrl?field('Source Version History',linkValue(historyUrl,'Open Version History')):''}</div><details class="record-history" open><summary>Previous Version Links <span class="record-heading-count">${versions.length}</span></summary>${versions.length?`<div class="record-history-list">${versions.map(v=>{const url=safeSourceUrl(v.sourcePageUrl,source);return`<div class="record-history-row"><div><b>${esc(v.version)}</b><span>${v.updatedDate?date(v.updatedDate):'Date not reported'}${v.fileSizeBytes?' · '+bytes(v.fileSizeBytes):''}</span></div>${linkValue(url,'Open Source Version')}</div>`}).join('')}</div>`:`<div class="record-history-empty">No source-provided previous-version links are available.${historyUrl?' Use the version history link above to check the source.':''}</div>`}</details></section></div>
 <section class="panel record-section record-description-section"><div class="record-section-head"><h2>Description</h2><button class="btn tiny" data-copy="${esc(description)}">Copy Description</button></div><div class="record-description" id="appDescription">${esc(description)}</div></section>
 <div class="record-bottom"><button class="btn" id="bottomBack">← Back to App Library</button></div></div>`;
}
'''
s=s[:a]+f+s[b:];p.write_text(s)
