from pathlib import Path
p=Path('public/ui/app.js');s=p.read_text()
def replace_function(name,code):
 global s
 start=s.index('function '+name+'(') if 'function '+name+'(' in s else s.index('async function '+name+'(')
 # Find next top-level function on a new line, not the end of a nested string.
 import re
 match=re.search(r'\n(?=(?:async )?function \w+\()',s[start+1:])
 assert match,name
 end=start+1+match.start()
 s=s[:start]+code.rstrip()+'\n'+s[end:]
# All library state is retained across UI refreshes.
s=s.replace('perPage:20,q:', 'perPage:32,q:')
s=s.replace("perPage:20,section:f.section", "perPage:f.perPage||32,section:f.section")
s=s.replace("if($('#topSub'))$('#topSub').textContent=m[1];", "if($('#topSub'))$('#topSub').textContent=m[1];if($('#newBtn'))$('#newBtn').hidden=S.tab==='library'||S.tab==='add';")
s=s.replace("if(S.tab!=='library')await go('library');S.addOpen=true;renderLibrary();setTimeout(()=>$('#sourceUrl')?.focus(),0)", "if(S.tab!=='library')await go('library');setTimeout(()=>$('#sourceUrl')?.focus(),0)")
# The legacy add route remains valid, but opens the same inline form.
s=s.replace("else if(tab==='add')renderImportPage();", "else if(tab==='add'){await loadLibrary();if(seq!==S.routeSeq)return;S.tab='library';setRoute('/library',{replace:true});updateHeader();renderLibrary();setTimeout(()=>$('#sourceUrl')?.focus(),0)}")
replace_function('libraryToolbar', '''function libraryToolbar(){const f=S.library,t=S.taxonomy||{},cats=Array.isArray(t.categories)?t.categories.filter(c=>f.section==='all'||c.section===f.section):[];return`<div class="library-filterbar"><div class="library-tabs"><button class="library-tab ${f.sort==='latest'?'active':''}" data-sort="latest">Latest</button><button class="library-tab ${f.sort==='popular'?'active':''}" data-sort="popular">Popular</button><button class="library-tab ${f.sort==='trending'?'active':''}" data-sort="trending">Trending</button></div><div class="library-sections"><button class="section-chip ${f.section==='all'?'active':''}" data-section="all">All Apps & Games</button><button class="section-chip ${f.section==='apps'?'active':''}" data-section="apps">Apps</button><button class="section-chip ${f.section==='games'?'active':''}" data-section="games">Games</button></div><select class="input library-category-select" id="libraryCategory" aria-label="Category"><option value="">All categories</option>${cats.map(c=>`<option value="${esc(c.slug)}" ${f.category===c.slug?'selected':''}>${esc(c.name)}</option>`).join('')}</select><div class="searchbar library-search"><span class="search-icon">${icon('search')}</span><input class="input" id="librarySearch" value="${esc(f.q)}" placeholder="Search apps" aria-label="Search apps"></div></div>`}''')
replace_function('inlineAddForm', '''function inlineAddForm(){return`<form id="inlineImportForm" class="inline-import-form"><input class="input" id="sourceUrl" type="url" required placeholder="Paste LiteAPKs app URL" aria-label="LiteAPKs app URL" autocomplete="off"><button class="btn primary" id="inlineImportApp" type="submit">Add</button></form><div id="inlineImportMsg" class="import-feedback" aria-live="polite"></div>`}''')
replace_function('importControls', '''function importControls(){const st=S.importState||{},active=['discovering','running'].includes(st.status);return`<form id="batchImportForm" class="import-control-grid"><input class="input" id="syncLimit" type="number" min="1" max="50000" step="1" value="${esc(S.importLimit||10)}" required aria-label="Number of apps to import" placeholder="Number of apps"><button class="btn primary" id="syncNow" type="submit" ${active?'disabled':''}>Import</button></form><div class="import-status" id="importStatus" aria-live="polite">${importStatusHtml(st)}</div><button class="btn tiny danger import-stop" id="stopSync" ${active||st.status==='paused'?'':'disabled'}>Stop</button>`}''')
replace_function('importStatusHtml', '''function importStatusHtml(st={}){const target=Number(st.requested_count||0),total=Number(st.total_count||0),processed=Number(st.processed_count||0),added=Number(st.inserted_count||0),percent=target?Math.min(100,Math.round(added/target*100)):total?Math.min(100,Math.round(processed/total*100)):0;return`<div class="import-status-line"><b>${esc(st.status||'idle')}</b><span>${fmt(added)}${target?' / '+fmt(target):''} added</span><span>${fmt(processed)} checked</span><span>${fmt(st.failed_count||0)} failed</span></div><div class="progress"><span style="width:${percent}%"></span></div>${st.last_error?`<div class="notice ${st.status==='paused'?'amber':'error'}">${esc(st.last_error)}</div>`:''}${st.status==='complete'&&target&&added<target?`<div class="helper">Only ${fmt(added)} new apps were available from the checked source pages. Nothing was invented or counted twice.</div>`:''}`;}''')
replace_function('updateImportState', '''function updateImportState(st){S.importState=st;const box=$('#importStatus');if(box)box.innerHTML=importStatusHtml(st);const active=['discovering','running'].includes(st.status);if($('#syncNow'))$('#syncNow').disabled=active;if($('#stopSync'))$('#stopSync').disabled=!(active||st.status==='paused')}''')
replace_function('scheduleImportPoll', '''function scheduleImportPoll(){clearTimeout(S.importTimer);if(!['running','discovering'].includes(S.importState?.status))return;S.importTimer=setTimeout(async()=>{try{const d=await API('/api/resolver/state');const previous=S.importState?.status;updateImportState(d.state||{});if(['running','discovering'].includes(S.importState.status))scheduleImportPoll();else if(['running','discovering'].includes(previous)){await refreshBootstrap();if(S.tab==='library'){await loadLibrary();renderLibrary()}}}catch(e){toast(e.message,'error')}},2000)}''')
replace_function('startManualImport', '''async function startManualImport(){const input=$('#syncLimit'),limit=Number(input?.value);if(!Number.isSafeInteger(limit)||limit<1||limit>50000)return toast('Enter a whole number from 1 to 50,000.','warning');S.importLimit=limit;const b=$('#syncNow');b.disabled=true;try{const d=await API('/api/resolver/sync',{method:'POST',body:JSON.stringify({mode:'new',limit})});updateImportState(d.state||{});scheduleImportPoll();toast('Import started.')}catch(e){toast(e.message,'error');b.disabled=false}}''')
replace_function('bindImportControls', '''function bindImportControls(){if($('#batchImportForm'))$('#batchImportForm').onsubmit=e=>{e.preventDefault();startManualImport()};if($('#stopSync'))$('#stopSync').onclick=stopManualImport;updateImportState(S.importState||{})}''')
replace_function('libraryResults', '''function libraryResults(){const p=S.pagination||{},cat=selectedCategory(),sectionLabel=S.library.section==='games'?'Games':S.library.section==='apps'?'Apps':'All Apps & Games',viewLabel=cat?.name||sectionLabel,title=S.library.sort==='popular'?`Popular · ${viewLabel}`:S.library.sort==='trending'?`Trending · ${viewLabel}`:viewLabel;return`<section class="panel library-results"><div class="library-results-head"><div><div class="panel-title">${esc(title)}</div><div class="panel-sub">Showing ${fmt(p.from||0)}–${fmt(p.to||0)} of ${fmt(p.total||0)} records. Page ${fmt(p.page||1)} of ${fmt(p.pages||1)}.</div></div>${S.library.category?`<button class="btn tiny" id="clearCategory">Back to ${esc(sectionLabel)}</button>`:''}</div>${libraryToolbar()}<div class="app-grid library-card-grid">${S.apps.length?S.apps.map(appRow).join(''):'<div class="empty app-grid-empty">No apps match this category.</div>'}</div><div class="library-pagination-row"><span>${fmt(S.library.perPage||32)} apps per page · ${fmt(p.total||0)} in this view</span>${pageButtons()}</div></section>`}''')
replace_function('renderLibrary', '''function renderLibrary(){const c=$('#content');c.innerHTML=`<section class="panel library-import-panel"><div class="library-import-grid"><div class="library-import-card"><h2>Auto Import</h2><p>Import new apps from LiteAPKs.</p>${importControls()}</div><div class="library-import-card"><h2>Add APK</h2><p>Paste one app link to add it directly.</p>${inlineAddForm()}</div></div></section>`+libraryResults();bindImportControls();if(['running','discovering'].includes(S.importState?.status))scheduleImportPoll();document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=async()=>{S.library.sort=b.dataset.sort;S.library.page=1;await go('library')});document.querySelectorAll('[data-section]').forEach(b=>b.onclick=async()=>{S.library.section=b.dataset.section;S.library.category='';S.library.page=1;await go('library')});if($('#libraryCategory'))$('#libraryCategory').onchange=async e=>{S.library.category=e.target.value||'';S.library.page=1;await go('library')};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;S.library.page=Number(b.dataset.page)||1;await go('library');window.scrollTo({top:0,behavior:'smooth'})});if($('#clearCategory'))$('#clearCategory').onclick=async()=>{S.library.category='';S.library.page=1;await go('library')};let timer=null;$('#librarySearch').oninput=e=>{clearTimeout(timer);const value=e.target.value;timer=setTimeout(async()=>{S.library.q=value.trim();S.library.page=1;await go('library',{replace:true})},450)};$('#inlineImportForm').onsubmit=async e=>{e.preventDefault();const b=$('#inlineImportApp'),url=$('#sourceUrl').value;b.disabled=true;$('#inlineImportMsg').innerHTML='<div class="notice">Resolving APK metadata…</div>';try{const d=await API('/api/apps/import',{method:'POST',body:JSON.stringify({sourcePageUrl:url})});toast(`${d.app.name} added`);await refreshBootstrap();await loadLibrary();renderLibrary();await openDetail(d.app.id)}catch(err){$('#inlineImportMsg').innerHTML=`<div class="notice error">${esc(err.message)}</div>`;b.disabled=false}};bindRows(c)}''')
# The legacy standalone import entry points now reuse the inline UI.
replace_function('renderImportPage', '''function renderImportPage(){go('library',{replace:true}).then(()=>$('#sourceUrl')?.focus()).catch(e=>toast(e.message,'error'))}''')
s=s.replace("S.importState=null,importOpen:false,addOpen:false", "S.importState=null,importLimit:10,importOpen:false,addOpen:false")
# Keep configured count when the shell is rerendered and do not add an extra header button.
p.write_text(s)
